#! /bin/sh

bspc config border_width           3
bspc config window_gap            20

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config focus_follows_pointer true

monintor_count=$(bspc query -M | wc -l)
if [[ $monintor_count == 1 ]]; then
    bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
elif [[ $monintor_count == 2 ]]; then
    bspc monitor eDP1 -d I II III IV V
    bspc monitor HDMI1 -d VI VII VIII IX X
fi

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a Firefox desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Screenkey manage=off

feh --bg-scale ~/Pictures/wallpapers/wallhaven-246428.png &
panel &
dunst &

sleep 1

stalonetray &
