#!/bin/zsh

bspc config border_width           2
bspc config window_gap            10
bspc config focused_border_color "#FFFFFF"
bspc config normal_border_color  "#000000"

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config focus_follows_pointer true

monintor_count=$(bspc query -M | wc -l)
if [[ $monintor_count == 1 ]]; then
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
elif [[ $monintor_count == 2 ]]; then
    bspc monitor eDP1 -d 6 7 8 9 10
    bspc monitor HDMI1 -d 1 2 3 4 5
fi

bspc rule -a Gimp desktop=^8 follow=on state=floating
bspc rule -a chromium desktop=^3 follow=on
bspc rule -a Firefox desktop=^2 follow=on
bspc rule -a MPlayer state=floating
bspc rule -a Screenkey manage=off
bspc rule -a XCalc:xcalc state=floating
bspc rule -a Gtkdialog:gtkdialog state=floating

sxhkd &
dunst &

if [ -f "$HOME/.config/bspwm/.$HOST" ]; then
    source "$HOME/.config/bspwm/.$HOST"
fi

panel &
sleep 5
stalonetray &
