#!/bin/zsh

if [ -f ~/.env ]; then
    . ~/.env
fi

eval $(setup_monitors)

bspc config border_width          $(echo "2 * $HIDPI_SCALE_FACTOR" | bc)
bspc config window_gap            $(echo "24 * $HIDPI_SCALE_FACTOR" | bc)
bspc config focused_border_color "#FFFFFF"
bspc config normal_border_color  "#756bb1"

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config focus_follows_pointer true

monintor_count=$(bspc query -M | wc -l)
if [[ $monintor_count == 1 ]]; then
    bspc monitor -d 1 2 3 4 5 6 7 8
elif [[ $monintor_count == 2 ]]; then
    bspc monitor $MON0 -d 6 7 8 9 10
    bspc monitor $MON1 -d 1 2 3 4 5
fi

bspc rule -a Gimp desktop=8 follow=on state=floating
bspc rule -a Gimp-2.8:gimp-2.8 desktop=8 follow=on state=floating
bspc rule -a chromium desktop=1 follow=on
bspc rule -a Firefox desktop=1 follow=on
bspc rule -a jetbrains-pycharm desktop=3 follow=on
bspc rule -a jetbrains-phpstorm desktop=4 follow=on
bspc rule -a MPlayer state=floating
bspc rule -a Screenkey manage=off
bspc rule -a XCalc:xcalc state=floating
bspc rule -a Gtkdialog:gtkdialog state=floating


setsid sxhkd &

pkill dunst
if [ "$HIDPI_SCALE_FACTOR" = "2" ]; then
    dunst -geom "600x9-12+60" -fn "Droid Sans Mono 18" &!
else
    dunst &
fi

if [ -f "$HOME/.config/bspwm/.$HOST" ]; then
    source "$HOME/.config/bspwm/.$HOST"
fi

setsid panel &

[ -f ~/.config/conky/.conkyrc.$HOST ] && conky -c ~/.config/conky/.conkyrc.$HOST &

sleep 1
if [[ $monintor_count == 2 || $HIDPI_SCALE_FACTOR == 1 ]]; then
    stalonetray -i 24 -geometry 1x1-570+0 &
else
    stalonetray &
fi

# fix for java apps
#wmname LG3D

# just place stalonetray above bar
sleep 1
xdo above -t "$(xdo id -a bar)" $(xdo id -n stalonetray) &

#chromium &

#bspc rule -a Termite:termite desktop=2 --one-shot
#termite &

#bspc rule -a MuPDF desktop=5
#mupdf ~/Dropbox/bachelor_informatica/Openstaand/Boeken/Antwoorden.pdf &
#mupdf ~/Dropbox/bachelor_informatica/Openstaand/Boeken/mips.pdf &

#blueman-applet &!

#sleep 1

#pycharm &
