#!/bin/zsh

bspc config border_width           2
bspc config window_gap            20
bspc config focused_border_color "#FFFFFF"
bspc config normal_border_color  "#000000"

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config focus_follows_pointer true

monintor_count=$(bspc query -M | wc -l)
if [[ $monintor_count == 1 ]]; then
    bspc monitor -d 1 2 3 4 5 6 7 8
elif [[ $monintor_count == 2 ]]; then
    bspc monitor eDP-1 -d 5 6 7 8
    bspc monitor HDMI-1 -d 1 2 3 4
fi

bspc rule -a Gimp desktop=8 follow=on state=floating
bspc rule -a Gimp-2.8:gimp-2.8 desktop=8 follow=on state=floating
bspc rule -a chromium desktop=1 follow=on
bspc rule -a Firefox desktop=1 follow=on
bspc rule -a jetbrains-pycharm desktop=3 follow=on
bspc rule -a jetbrains-phpstorm desktop=4 follow=on
bspc rule -a MPlayer state=floating
bspc rule -a Screenkey manage=off
bspc rule -a XCalc:xcalc state=floating
bspc rule -a Gtkdialog:gtkdialog state=floating

#bspc rule -a Termite:termite desktop=2 --one-shot

bspc desktop 1 -l monocle
bspc desktop 2 -l monocle
bspc desktop 3 -l monocle
bspc desktop 4 -l monocle

eval $(setup_monitors)

#if [ "$HIDPI_SCALE_FACTOR" = "1" ]; then
#    xrdb -merge ~/.Xresources.standing &> xprofile.log
#fi

setsid sxhkd &
dunst &

if [ -f "$HOME/.config/bspwm/.$HOST" ]; then
    source "$HOME/.config/bspwm/.$HOST"
fi

setsid panel &
sleep 5
if [[ $monintor_count == 2 ]]; then
    stalonetray -i 24 -geometry 1x1-570+0 &
else
    stalonetray &
fi

# fix for java apps
wmname LG3D

#chromium &
#termite &
#
#bspc rule -a mupdf desktop=5
#mupdf /home/dino/Dropbox/Bachelor\ Informatica/Openstaand/Kansrekening\ en\ Statistiek\ \(TI2216M\)\ Q1/Boeken,\ Readers,\ Dictaat/Antwoorden.pdf
#mupdf ~/Dropbox/Bachelor\ Informatica/Openstaand/TI2216M/Introduction\ to\ Probability\ and\ Statistics.pdf
