# hypridle config. See https://wiki.hypr.land/Hypr-Ecosystem/hypridle/
# Waybar's idle inhibitor (eye icon) pauses all of this while it's on.

general {
    lock_cmd = pidof hyprlock || hyprlock                             # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session                          # lock before suspend.
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({action = "on"})' # turn on screen w/o key press after resume.
}

listener {
    timeout = 150                                # 2.5min.
    on-timeout = brightnessctl -s set 10         # dim laptop backlight.
    on-resume = brightnessctl -r                 # restore laptop backlight.
}

listener {
    timeout = 300                                 # 5min.
    on-timeout = loginctl lock-session            # lock screen.
}

listener {
    timeout = 330                                                 # 5.5min.
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({action = "off"})' # screens off.
    on-resume = hyprctl dispatch 'hl.dsp.dpms({action = "on"})'   # screens on when activity is detected.
}
